const $=id=>document.getElementById(id);
const state={format:"16:9",live:false,selectedScene:"scene-1",programScene:"scene-1",previewScene:"scene-2",transition:"CUT",ticker:"",mediaItems:[],sources:new Map(),scenes:[{id:"scene-1",name:"Camera 1",layers:[{id:"l1",source:"camera1",x:0,y:0,w:1,h:1,opacity:1,visible:true}]},{id:"scene-2",name:"Camera 2",layers:[{id:"l2",source:"camera2",x:0,y:0,w:1,h:1,opacity:1,visible:true}]},{id:"scene-3",name:"Interview",layers:[{id:"l3",source:"camera1",x:0,y:0,w:.68,h:1,opacity:1,visible:true},{id:"l4",source:"camera2",x:.68,y:.12,w:.32,h:.88,opacity:1,visible:true}]},{id:"scene-4",name:"Screen + Cam",layers:[{id:"l5",source:"screen",x:0,y:0,w:1,h:1,opacity:1,visible:true},{id:"l6",source:"camera1",x:.72,y:.7,w:.26,h:.26,opacity:1,visible:true}]},{id:"scene-5",name:"Media",layers:[]}]};
const canvases={program:$('programCanvas'),preview:$('previewCanvas')},ctx={program:$('programCanvas').getContext('2d'),preview:$('previewCanvas').getContext('2d')},videos=new Map(),images=new Map();
function toast(m){const e=$('toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),2200)}
function scene(id){return state.scenes.find(s=>s.id===id)}function selected(){return scene(state.selectedScene)||state.scenes[0]}function label(id){return scene(id)?.name||id}
function provider(raw){try{const h=new URL(raw).hostname.toLowerCase().replace(/^www\./,'').replace(/^m\./,'');if(['youtube.com','youtu.be','youtube-nocookie.com'].includes(h))return'youtube';if(['vimeo.com','player.vimeo.com'].includes(h))return'vimeo';return'direct'}catch{return'invalid'}}
function ytId(raw){try{const u=new URL(raw);if(u.hostname.includes('youtu.be'))return u.pathname.split('/').filter(Boolean)[0];if(u.pathname.includes('/shorts/'))return u.pathname.split('/shorts/')[1].split('/')[0];if(u.pathname.includes('/embed/'))return u.pathname.split('/embed/')[1].split('/')[0];return u.searchParams.get('v')}catch{return null}}
function vmId(raw){try{return new URL(raw).pathname.match(/(?:video\/)?(\d+)/)?.[1]||null}catch{return null}}
function embedSrc(item){if(item.provider==='youtube'){const id=ytId(item.url);return id?`https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?enablejsapi=1&playsinline=1&controls=1&rel=0&origin=${encodeURIComponent(location.origin)}`:null}if(item.provider==='vimeo'){const id=vmId(item.url);return id?`https://player.vimeo.com/video/${encodeURIComponent(id)}?autoplay=0&title=0&byline=0&portrait=0`:null}return null}
function embedFor(which,item){const f=$(which==='program'?'programEmbed':'previewEmbed'),src=embedSrc(item);if(!f||!src)return;f.src=src;f.hidden=false;f.style.display='block';f.style.position='absolute';f.style.left='0';f.style.top='0';f.style.width='100%';f.style.height='100%';f.style.zIndex='15'}
function hideEmbed(which){const f=$(which==='program'?'programEmbed':'previewEmbed');if(f){f.hidden=true;f.style.display='none';f.removeAttribute('src')}}
async function capture(source){if(state.sources.has(source))return state.sources.get(source);try{const stream=source==='screen'?await navigator.mediaDevices.getDisplayMedia({video:true,audio:true}):await navigator.mediaDevices.getUserMedia({video:{facingMode:source==='camera1'?'environment':'user',width:{ideal:1920},height:{ideal:1080}},audio:true});const v=document.createElement('video');v.srcObject=stream;v.autoplay=true;v.playsInline=true;v.muted=true;await v.play().catch(()=>{});videos.set(source,v);const item={id:source,name:source==='screen'?'Screen share':source==='camera1'?'Camera 1':'Camera 2',kind:'stream',stream};state.sources.set(source,item);return item}catch(e){toast('Camera or screen permission was denied');return null}}
function mediaVideo(item){let v=videos.get(item.id);if(v)return v;v=document.createElement('video');v.src=item.url;v.preload='auto';v.playsInline=true;v.crossOrigin='anonymous';v.onerror=()=>toast('This direct media URL is not playable by this browser');videos.set(item.id,v);return v}
function imageEl(item){let i=images.get(item.id);if(i)return i;i=new Image();i.src=item.url;i.onload=render;images.set(item.id,i);return i}
async function draw(which,id){const c=ctx[which],can=canvases[which];c.fillStyle='#05070a';c.fillRect(0,0,can.width,can.height);const s=scene(id);if(!s)return;let external=null;for(const l of s.layers){if(!l.visible)continue;const item=['camera1','camera2','screen'].includes(l.source)?await capture(l.source):state.sources.get(l.source);if(!item)continue;if(item.kind==='embed'){external=item;continue}const x=l.x*can.width,y=l.y*can.height,w=l.w*can.width,h=l.h*can.height;c.save();c.globalAlpha=l.opacity??1;if(item.kind==='stream'||item.kind==='media'){const v=videos.get(item.id);if(v?.readyState>=2)c.drawImage(v,x,y,w,h)}else if(item.kind==='image'){const im=imageEl(item);if(im.complete&&im.naturalWidth)c.drawImage(im,x,y,w,h)}else if(item.kind==='text'){c.fillStyle='#fff';c.font='700 42px system-ui';c.fillText(l.text||'LIVE',x,y+50)}else if(item.kind==='graphic'){c.fillStyle='#070a10e8';c.fillRect(x,y,w,h);c.fillStyle=item.graphic.color;c.fillRect(x,y,5,h);c.fillStyle='#fff';c.font='700 38px system-ui';c.fillText(item.graphic.name,x+22,y+55);c.fillStyle='#b9c4d2';c.font='22px system-ui';c.fillText(item.graphic.role,x+22,y+88)}c.restore()}if(external)embedFor(which,external);else hideEmbed(which)}
async function render(){await draw('program',state.programScene);await draw('preview',state.previewScene);update();renderScenes();renderLayers();renderSourceSelection()}
function update(){$('programLabel').textContent=label(state.programScene);$('programSource').textContent=label(state.programScene);$('previewLabel').textContent=label(state.previewScene);$('previewSource').textContent=label(state.previewScene);$('transitionStatus').textContent=state.transition;$('selectedSceneName').textContent=label(state.selectedScene);$('layerCount').textContent=(selected()?.layers.length||0)+' layers';$('formatPill').textContent=state.format}
function renderScenes(){const g=$('sceneGrid');if(!g)return;g.innerHTML='';state.scenes.forEach(s=>{const b=document.createElement('button');b.className='scene '+(s.id===state.programScene?'program ':'')+(s.id===state.previewScene?'preview ':'')+(s.id===state.selectedScene?'selected':'');b.innerHTML=`<b>${s.name}</b><small>${s.layers.length} layers</small><em>${s.id===state.programScene?'PROGRAM':s.id===state.previewScene?'PREVIEW':'READY'}</em>`;b.onclick=()=>{state.selectedScene=s.id;state.previewScene=s.id;render();toast('Preview: '+s.name)};g.appendChild(b)})}
function layerName(l){if(l.source==='camera1')return'Camera 1';if(l.source==='camera2')return'Camera 2';if(l.source==='screen')return'Screen share';if(l.source==='text')return'Text';return state.sources.get(l.source)?.name||'Media'}
function renderLayers(){const list=$('layerList');if(!list)return;list.innerHTML='';selected().layers.forEach((l,i)=>{const r=document.createElement('div');r.className='layer-row';r.innerHTML=`<button class="vis">${l.visible?'◉':'○'}</button><div><b>${layerName(l)}</b><small>Layer ${i+1}</small></div><input class="opacity" type="range" min="0" max="100" value="${Math.round((l.opacity??1)*100)}"><button class="up">↑</button><button class="down">↓</button><button class="remove">×</button>`;r.querySelector('.vis').onclick=()=>{l.visible=!l.visible;render()};r.querySelector('.opacity').oninput=e=>{l.opacity=+e.target.value/100;render()};r.querySelector('.up').onclick=()=>{if(i){[selected().layers[i-1],selected().layers[i]]=[selected().layers[i],selected().layers[i-1]];render()}};r.querySelector('.down').onclick=()=>{if(i<selected().layers.length-1){[selected().layers[i+1],selected().layers[i]]=[selected().layers[i],selected().layers[i+1]];render()}};r.querySelector('.remove').onclick=()=>{selected().layers.splice(i,1);render()};list.appendChild(r)})}
function renderSourceSelection(){document.querySelectorAll('.source-card').forEach(b=>b.classList.toggle('selected',b.dataset.source===selected().layers[0]?.source))}
async function selectSource(source){if(source==='media'){ $('mediaUrl').focus();toast('Paste a URL then press Add source');return}if(source==='image'){ $('addImageBtn').click();return}if(source==='graphic'){ $('lowerName').focus();return}await capture(source);selected().layers=[{id:'layer-'+Date.now(),source,x:0,y:0,w:1,h:1,opacity:1,visible:true}];state.previewScene=state.selectedScene;render()}
async function addLayer(source){if(source==='media'){const item=state.mediaItems.at(-1);if(!item)return toast('Add a media source first');source=item.id}else if(source==='image'){const item=[...state.sources.values()].find(x=>x.kind==='image');if(!item)return toast('Choose an image first');source=item.id}else if(source==='text'){selected().layers.push({id:'layer-'+Date.now(),source:'text',text:'LIVE',x:.05,y:.08,w:.4,h:.1,opacity:1,visible:true});return render()}else if(['camera1','camera2','screen'].includes(source))await capture(source);const n=selected().layers.length;selected().layers.push({id:'layer-'+Date.now(),source,x:n%2?.55:0,y:n>1?.55:0,w:.45,h:.45,opacity:1,visible:true});state.previewScene=state.selectedScene;render()}
function addMedia(){const url=$('mediaUrl').value.trim();if(!url)return toast('Paste a URL first');const p=provider(url);if(p==='invalid')return toast('Invalid URL');const id='media-'+Date.now(),item={id,name:p==='youtube'?'YouTube video':p==='vimeo'?'Vimeo video':'Media '+(state.mediaItems.length+1),kind:p==='direct'?'media':'embed',provider:p,url};if(item.kind==='embed'&&!embedSrc(item))return toast('Could not identify that video');state.mediaItems.push(item);state.sources.set(id,item);selected().layers=[{id:'layer-'+Date.now(),source:id,x:0,y:0,w:1,h:1,opacity:1,visible:true}];state.previewScene=state.selectedScene;renderMediaList();render();toast('Added to Preview')}
function addImage(url){if(!url)return toast('Choose an image first');const id='image-'+Date.now(),item={id,name:'Image',kind:'image',url};state.sources.set(id,item);selected().layers=[{id:'layer-'+Date.now(),source:id,x:0,y:0,w:1,h:1,opacity:1,visible:true}];state.previewScene=state.selectedScene;render()}
function addGraphic(){const id='graphic-'+Date.now(),item={id,name:'Lower Third',kind:'graphic',graphic:{name:$('lowerName').value||'Our Production Studio',role:$('lowerRole').value||'Live',color:$('lowerColor').value}};state.sources.set(id,item);selected().layers.push({id:'layer-'+Date.now(),source:id,x:.04,y:.72,w:.7,h:.18,opacity:1,visible:true});render()}
function renderMediaList(){const l=$('mediaList');if(!l)return;l.innerHTML='';state.mediaItems.forEach(item=>{const r=document.createElement('div');r.className='media-item';r.innerHTML=`<span class="media-name">${item.name}</span><span class="media-kind">${item.provider?.toUpperCase()||'VIDEO'}</span><button class="prev">Preview</button><button class="play">▶</button><button class="del">×</button>`;r.querySelector('.prev').onclick=()=>{selected().layers=[{id:'layer-'+Date.now(),source:item.id,x:0,y:0,w:1,h:1,opacity:1,visible:true}];state.previewScene=state.selectedScene;render()};r.querySelector('.play').onclick=()=>{if(item.kind==='embed'){embedFor('preview',item);$('previewEmbed').contentWindow?.postMessage(JSON.stringify({event:'command',func:'playVideo',args:[]}),'*')}else mediaVideo(item).play().catch(()=>toast('Playback blocked or URL invalid'))};r.querySelector('.del').onclick=()=>{state.mediaItems=state.mediaItems.filter(x=>x.id!==item.id);state.sources.delete(item.id);renderMediaList();render()};l.appendChild(r)})}
function currentMedia(){const l=scene(state.previewScene)?.layers.find(x=>x.source.startsWith('media-'));return l?state.sources.get(l.source):null}
function mediaControl(a){const item=currentMedia();if(!item)return toast('Select a media scene first');if(item.kind==='embed'){embedFor('preview',item);const f=$('previewEmbed'),func=a==='play'?'playVideo':a==='pause'?'pauseVideo':'stopVideo';f.contentWindow?.postMessage(JSON.stringify({event:'command',func,args:[]}),'*');return}const v=mediaVideo(item);if(a==='play')v.play().catch(()=>toast('Playback blocked or URL invalid'));if(a==='pause')v.pause();if(a==='stop'){v.pause();v.currentTime=0}}
function take(fade){if(state.previewScene===state.programScene)return toast('Preview is already Program');state.programScene=state.previewScene;state.transition=fade?'FADE':'CUT';render();if(fade)$('programFrame').animate([{opacity:1},{opacity:.25},{opacity:1}],{duration:450})}
function swap(){[state.programScene,state.previewScene]=[state.previewScene,state.programScene];state.selectedScene=state.previewScene;render()}
$('takeBtn').onclick=()=>take(false);$('fadeBtn').onclick=()=>take(true);$('swapBtn').onclick=swap;$('addMediaBtn').onclick=addMedia;$('addImageBtn').onclick=()=>$('imageFile').click();$('imageFile').onchange=e=>{const f=e.target.files[0];if(f)addImage(URL.createObjectURL(f))};$('videoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const id='media-'+Date.now(),item={id,name:f.name,kind:'media',url:URL.createObjectURL(f)};state.mediaItems.push(item);state.sources.set(id,item);selected().layers=[{id:'layer-'+Date.now(),source:id,x:0,y:0,w:1,h:1,opacity:1,visible:true}];state.previewScene=state.selectedScene;renderMediaList();render()};$('cameraBtn').onclick=()=>selectSource('camera1');$('screenBtn').onclick=()=>selectSource('screen');$('addGraphicBtn').onclick=addGraphic;$('tickerBtn').onclick=()=>{state.ticker=$('tickerText').value;render()};$('playPauseBtn').onclick=()=>{const i=currentMedia();if(!i)return toast('Select a media scene first');if(i.kind==='embed'){mediaControl('play')}else{const v=mediaVideo(i);v.paused?mediaControl('play'):mediaControl('pause')}};$('stopMediaBtn').onclick=()=>mediaControl('stop');$('restartMediaBtn').onclick=()=>mediaControl('play');$('mediaVolume').oninput=e=>{const i=currentMedia();if(i?.kind==='media')mediaVideo(i).volume=+e.target.value/100};$('formatSelect').onchange=e=>{state.format=e.target.value;render()};$('goLiveBtn').onclick=()=>{state.live=!state.live;$('goLiveBtn').textContent=state.live?'END LIVE':'GO LIVE';$('streamState').textContent=state.live?'Production active':'Offline';$('connectionDot').classList.toggle('good',state.live)};$('recordBtn').onclick=()=>toast('Recording will be connected to the broadcast engine next');$('addSceneBtn').onclick=()=>{const n=prompt('Scene name','New Scene');if(!n)return;const id='scene-'+Date.now();state.scenes.push({id,name:n,layers:[]});state.selectedScene=id;state.previewScene=id;render()};
document.querySelectorAll('.source-card[data-source]').forEach(b=>b.onclick=()=>selectSource(b.dataset.source));document.querySelectorAll('[data-add-layer]').forEach(b=>b.onclick=()=>addLayer(b.dataset.add-layer));
renderMediaList();render();setInterval(()=>{draw('program',state.programScene);draw('preview',state.previewScene)},1000/30);setInterval(()=>{const d=new Date();$('programClock').textContent=[d.getHours(),d.getMinutes(),d.getSeconds()].map(x=>String(x).padStart(2,'0')).join(':')},1000);